import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Home/Hero";
export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Bugacademy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>

			<Hero />
		</div>
	);
}
