import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Home/Hero";
import AboutHero from "../components/Home/AboutHero";
import CourseHero from "../components/Home/CourseHero";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Bugacademy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favico.png" />
			</Head>

			<Hero />
			<AboutHero />
			<CourseHero />
			<a className='mb-36 p-4 text-center mx-32 rounded-xl bg-green-800 w-8' href="https://pay.squadco.com/HNPW48">Order Now</a>
			
		</div>
	);
}
